services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./api/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_DB: ${DB_NAME:-members_api}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
    ports:
      - "5433:5433"
    command: postgres -p 5433 
    networks:
      - django-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-members_api}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    container_name: django-docker
    #command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env.test
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - django-network

  spa:
    build: ./spa
    volumes:
      - ./spa:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    networks:
      - django-network

volumes:
  postgres_data:

networks:
  django-network:
    driver: bridge